/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author danyal
 */
public class BarcodeDisplay extends javax.swing.JFrame {

    /**
     * Creates new form barcodeDisplay
     */
    public BarcodeDisplay() throws Exception {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        usr_barcode.setIcon(new ImageIcon(General.generateBarcode(Integer.toString(UserAdd.getID()))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usr_barcode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usr_barcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usr_barcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usr_barcodeMouseClicked(evt);
            }
        });
        getContentPane().add(usr_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 430, 140));

        setSize(new java.awt.Dimension(669, 356));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usr_barcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usr_barcodeMouseClicked
        try {
            ImageIcon icon = new ImageIcon(General.generateBarcode("1000000001"));
            usr_barcode.setIcon(icon);
        } catch (Exception ex) {
            Logger.getLogger(UserAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usr_barcodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarcodeDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarcodeDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarcodeDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarcodeDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BarcodeDisplay().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(BarcodeDisplay.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel usr_barcode;
    // End of variables declaration//GEN-END:variables
}
