/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author danyal
 */
public class BookAdd extends javax.swing.JFrame {

    private ArrayList<String> genre_list = new ArrayList<>();

    /**
     * Creates new form BookAdd
     */
    public BookAdd() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        book_isbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        label_fname = new javax.swing.JLabel();
        book_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        label_fname1 = new javax.swing.JLabel();
        book_author = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        label_fname2 = new javax.swing.JLabel();
        book_publisher = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        label_fname3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        book_genre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        book_copiesOwned = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        label_fname7 = new javax.swing.JLabel();
        book_datePublished = new com.toedter.calendar.JDateChooser();
        book_dateAdded = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 205, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Book To Collection");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, 860, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        book_isbn.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        book_isbn.setForeground(new java.awt.Color(0, 0, 0));
        book_isbn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 205, 60), 1, true));
        book_isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                book_isbnFocusLost(evt);
            }
        });
        getContentPane().add(book_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 380, 40));
        book_isbn.setBorder(BorderFactory.createCompoundBorder(
            book_isbn.getBorder(),
            BorderFactory.createEmptyBorder(0, 6, 0, 6)));

    jLabel4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
    jLabel4.setText("ISBN");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

    label_fname.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
    label_fname.setForeground(new java.awt.Color(255, 2, 0));
    label_fname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-high-importance-15-2.png"))); // NOI18N
    label_fname.setText("Invalid ISBN!");
    getContentPane().add(label_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));
    label_fname.setVisible(false);

    book_name.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
    book_name.setForeground(new java.awt.Color(0, 0, 0));
    book_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 205, 60), 1, true));
    book_name.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            book_nameFocusLost(evt);
        }
    });
    getContentPane().add(book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 380, 40));
    book_isbn.setBorder(BorderFactory.createCompoundBorder(
        book_isbn.getBorder(),
        BorderFactory.createEmptyBorder(0, 6, 0, 6)));

jLabel5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
jLabel5.setText("Name");
getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

label_fname1.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
label_fname1.setForeground(new java.awt.Color(255, 2, 0));
label_fname1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-high-importance-15-2.png"))); // NOI18N
label_fname1.setText("Invalid Book Name!");
getContentPane().add(label_fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, 20));
label_fname.setVisible(false);

book_author.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
book_author.setForeground(new java.awt.Color(0, 0, 0));
book_author.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 205, 60), 1, true));
book_author.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusLost(java.awt.event.FocusEvent evt) {
        book_authorFocusLost(evt);
    }
    });
    getContentPane().add(book_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 380, 40));
    book_isbn.setBorder(BorderFactory.createCompoundBorder(
        book_isbn.getBorder(),
        BorderFactory.createEmptyBorder(0, 6, 0, 6)));

jLabel6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
jLabel6.setText("Author");
getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

label_fname2.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
label_fname2.setForeground(new java.awt.Color(255, 2, 0));
label_fname2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-high-importance-15-2.png"))); // NOI18N
label_fname2.setText("Invalid Author Name!");
getContentPane().add(label_fname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));
label_fname.setVisible(false);

book_publisher.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
book_publisher.setForeground(new java.awt.Color(0, 0, 0));
book_publisher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 205, 60), 1, true));
book_publisher.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusLost(java.awt.event.FocusEvent evt) {
        book_publisherFocusLost(evt);
    }
    });
    getContentPane().add(book_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 380, 40));
    book_isbn.setBorder(BorderFactory.createCompoundBorder(
        book_isbn.getBorder(),
        BorderFactory.createEmptyBorder(0, 6, 0, 6)));

jLabel7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
jLabel7.setText("Publisher");
getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

label_fname3.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
label_fname3.setForeground(new java.awt.Color(255, 2, 0));
label_fname3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-high-importance-15-2.png"))); // NOI18N
label_fname3.setText("Invalid Publisher Name!");
getContentPane().add(label_fname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, 20));
label_fname.setVisible(false);

jLabel8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
jLabel8.setText("Date Published");
getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

jLabel9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
jLabel9.setText("Date Added To Library");
getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

book_genre.setEditable(false);
book_genre.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
book_genre.setForeground(new java.awt.Color(0, 0, 0));
book_genre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 205, 60), 1, true));
book_genre.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusLost(java.awt.event.FocusEvent evt) {
        book_genreFocusLost(evt);
    }
    });
    getContentPane().add(book_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 380, 40));
    book_isbn.setBorder(BorderFactory.createCompoundBorder(
        book_isbn.getBorder(),
        BorderFactory.createEmptyBorder(0, 6, 0, 6)));

jLabel10.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
jLabel10.setText("Book Genre");
getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

book_copiesOwned.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
book_copiesOwned.setForeground(new java.awt.Color(0, 0, 0));
book_copiesOwned.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 205, 60), 1, true));
book_copiesOwned.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusLost(java.awt.event.FocusEvent evt) {
        book_copiesOwnedFocusLost(evt);
    }
    });
    getContentPane().add(book_copiesOwned, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 380, 40));
    book_isbn.setBorder(BorderFactory.createCompoundBorder(
        book_isbn.getBorder(),
        BorderFactory.createEmptyBorder(0, 6, 0, 6)));

jLabel11.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
jLabel11.setText("Copies Owned");
getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

label_fname7.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
label_fname7.setForeground(new java.awt.Color(255, 2, 0));
label_fname7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-high-importance-15-2.png"))); // NOI18N
label_fname7.setText("Invalid Entry!");
getContentPane().add(label_fname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, 20));
label_fname.setVisible(false);

book_datePublished.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 60)));
book_datePublished.setForeground(new java.awt.Color(255, 255, 255));
book_datePublished.setDateFormatString("MMM d, yyyy");
book_datePublished.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
getContentPane().add(book_datePublished, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 380, 40));

book_dateAdded.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 60)));
book_dateAdded.setForeground(new java.awt.Color(255, 255, 255));
book_dateAdded.setDateFormatString("MMM d, yyyy");
book_dateAdded.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
getContentPane().add(book_dateAdded, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 380, 40));

jLabel1.setBackground(new java.awt.Color(255, 255, 255));
jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel1.setText("young-adult");
jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel1MouseClicked(evt);
    }
    });
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 80, 30));

    jLabel3.setBackground(new java.awt.Color(255, 255, 255));
    jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("romance");
    jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel3MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 60, 30));

    jLabel13.setBackground(new java.awt.Color(255, 255, 255));
    jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel13.setText("fiction");
    jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel13MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 50, 30));

    jLabel14.setBackground(new java.awt.Color(255, 255, 255));
    jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel14.setText("fantasy");
    jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel14MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 60, 30));

    jLabel15.setBackground(new java.awt.Color(255, 255, 255));
    jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel15.setText("sci-fi");
    jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel15MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 40, 30));

    jLabel16.setBackground(new java.awt.Color(255, 255, 255));
    jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel16.setText("children");
    jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel16MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 60, 30));

    jLabel17.setBackground(new java.awt.Color(255, 255, 255));
    jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel17.setText("non-fiction");
    jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel17MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 70, 30));

    jLabel18.setBackground(new java.awt.Color(255, 255, 255));
    jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel18.setText("history");
    jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel18MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 50, 30));

    jLabel19.setBackground(new java.awt.Color(255, 255, 255));
    jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel19.setText("covers");
    jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel19MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 50, 30));

    jLabel20.setBackground(new java.awt.Color(255, 255, 255));
    jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel20.setText("best");
    jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel20MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 40, 30));

    jLabel21.setBackground(new java.awt.Color(255, 255, 255));
    jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel21.setText("mystery");
    jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel21MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 60, 30));

    jLabel22.setBackground(new java.awt.Color(255, 255, 255));
    jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel22.setText("horror");
    jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel22MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 50, 30));

    jLabel23.setBackground(new java.awt.Color(255, 255, 255));
    jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel23.setText("historical-fiction");
    jLabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel23MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 110, 30));

    jLabel24.setBackground(new java.awt.Color(255, 255, 255));
    jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel24.setText("suspense");
    jLabel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel24MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 70, 30));

    jLabel25.setBackground(new java.awt.Color(255, 255, 255));
    jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel25.setText("paranormal");
    jLabel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel25MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 80, 30));

    jLabel26.setBackground(new java.awt.Color(255, 255, 255));
    jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel26.setText("love");
    jLabel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel26MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 40, 30));

    jLabel27.setBackground(new java.awt.Color(255, 255, 255));
    jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel27.setText("biography");
    jLabel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel27MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 70, 30));

    jLabel28.setBackground(new java.awt.Color(255, 255, 255));
    jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel28.setText("thriller");
    jLabel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel28MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 50, 30));

    jLabel29.setBackground(new java.awt.Color(255, 255, 255));
    jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel29.setText("women");
    jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel29MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 50, 30));

    jLabel30.setBackground(new java.awt.Color(255, 255, 255));
    jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel30.setText("series");
    jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel30MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 50, 30));

    jLabel31.setBackground(new java.awt.Color(255, 255, 255));
    jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel31.setText("contemporary");
    jLabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel31MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 90, 30));

    jLabel32.setBackground(new java.awt.Color(255, 255, 255));
    jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel32.setText("titles");
    jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel32MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 40, 30));

    jLabel33.setBackground(new java.awt.Color(255, 255, 255));
    jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel33.setText("classics");
    jLabel33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel33MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 60, 30));

    jLabel34.setBackground(new java.awt.Color(255, 255, 255));
    jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel34.setText("graphic novels");
    jLabel34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel34MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 90, 30));

    jLabel35.setBackground(new java.awt.Color(255, 255, 255));
    jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel35.setText("memoir");
    jLabel35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 135, 238), 2, true));
    jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel35MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 50, 30));

    setSize(new java.awt.Dimension(860, 712));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void book_isbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_isbnFocusLost
        if (General.validateField(book_isbn, General.TEXT_REGEX)) {
            General.fieldErrorDisplayOff(book_isbn, label_fname);
        } else {
            General.fieldErrorDisplayOn(book_isbn, label_fname);
        }
    }//GEN-LAST:event_book_isbnFocusLost

    private void book_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_nameFocusLost
        if (General.validateField(book_isbn, General.TEXT_REGEX)) {
            General.fieldErrorDisplayOff(book_isbn, label_fname);
        } else {
            General.fieldErrorDisplayOn(book_isbn, label_fname);
        }
    }//GEN-LAST:event_book_nameFocusLost

    private void book_authorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_authorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_book_authorFocusLost

    private void book_publisherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_publisherFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_book_publisherFocusLost

    private void book_genreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_genreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_book_genreFocusLost

    private void book_copiesOwnedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_book_copiesOwnedFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_book_copiesOwnedFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        genre_select(jLabel3);
        changeLabelBg(jLabel3);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        genre_select(jLabel13);
        changeLabelBg(jLabel13);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        genre_select(jLabel1);
        changeLabelBg(jLabel1);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        genre_select(jLabel14);
        changeLabelBg(jLabel14);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        genre_select(jLabel28);
        changeLabelBg(jLabel28);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        genre_select(jLabel15);
        changeLabelBg(jLabel15);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        genre_select(jLabel16);
        changeLabelBg(jLabel16);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        genre_select(jLabel17);
        changeLabelBg(jLabel17);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        genre_select(jLabel18);
        changeLabelBg(jLabel18);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        genre_select(jLabel22);
        changeLabelBg(jLabel22);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        genre_select(jLabel20);
        changeLabelBg(jLabel20);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        genre_select(jLabel19);
        changeLabelBg(jLabel19);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        genre_select(jLabel25);
        changeLabelBg(jLabel25);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        genre_select(jLabel21);
        changeLabelBg(jLabel21);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        genre_select(jLabel24);
        changeLabelBg(jLabel24);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        genre_select(jLabel27);
        changeLabelBg(jLabel27);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        genre_select(jLabel29);
        changeLabelBg(jLabel29);
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        genre_select(jLabel30);
        changeLabelBg(jLabel30);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        genre_select(jLabel31);
        changeLabelBg(jLabel31);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        genre_select(jLabel26);
        changeLabelBg(jLabel26);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        genre_select(jLabel34);
        changeLabelBg(jLabel34);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        genre_select(jLabel32);
        changeLabelBg(jLabel32);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        genre_select(jLabel33);
        changeLabelBg(jLabel33);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        genre_select(jLabel35);
        changeLabelBg(jLabel35);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        genre_select(jLabel23);
        changeLabelBg(jLabel23);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void genre_select(JLabel x) {
        Color labelColour = x.getBackground();

        if (labelColour.getRed() == 255) {
            if (!(book_genre.getText().equals(""))) {
                book_genre.setText(book_genre.getText() + ", " + x.getText());
            } else {
                book_genre.setText(x.getText());
            }
            genre_list.add(x.getText());
            System.out.println(genre_list);
        } else {
            genre_list.remove(x.getText());
            book_genre.setText("");
            genre_list.forEach(item -> {
                if (!(book_genre.getText().equals(""))) {
                    book_genre.setText(book_genre.getText() + ", " + item);
                } else {
                    book_genre.setText(item);
                }
            });
        }
    }

    private void changeLabelBg(JLabel x) {
        Color labelColour = x.getBackground();

        if (labelColour.getRed() == 255) {
            x.setBackground(new Color(66, 135, 238));
            x.setOpaque(true);
            x.setForeground(Color.white);
        } else {
            x.setBackground(Color.white);
            x.setForeground(new Color(0, 0, 0));
            x.setOpaque(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windnows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField book_author;
    private javax.swing.JTextField book_copiesOwned;
    private com.toedter.calendar.JDateChooser book_dateAdded;
    private com.toedter.calendar.JDateChooser book_datePublished;
    private javax.swing.JTextField book_genre;
    private javax.swing.JTextField book_isbn;
    private javax.swing.JTextField book_name;
    private javax.swing.JTextField book_publisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_fname;
    private javax.swing.JLabel label_fname1;
    private javax.swing.JLabel label_fname2;
    private javax.swing.JLabel label_fname3;
    private javax.swing.JLabel label_fname7;
    // End of variables declaration//GEN-END:variables
}
